src/java/entities/Roles.java
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package entities;

import java.io.Serializable;
import java.util.Collection;
import javax.persistence.Basic;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.ManyToMany;
import javax.persistence.NamedQueries;
import javax.persistence.NamedQuery;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.validation.constraints.Size;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlTransient;

/**
 *
 * @author broja
 */
@Entity
@Table(name = "roles", catalog = "vetsoft", schema = "public")
@XmlRootElement
@NamedQueries({
    @NamedQuery(name = "Roles.findAll", query = "SELECT r FROM Roles r"),
    @NamedQuery(name = "Roles.findByIdRol", query = "SELECT r FROM Roles r WHERE r.idRol = :idRol"),
    @NamedQuery(name = "Roles.findByNombreRol", query = "SELECT r FROM Roles r WHERE r.nombreRol = :nombreRol")})
public class Roles implements Serializable {

    private static final long serialVersionUID = 1L;
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Basic(optional = false)
    @Column(name = "id_rol")
    private Integer idRol;
    @Size(max = 50)
    @Column(name = "nombre_rol")
    private String nombreRol;
    @ManyToMany(mappedBy = "rolesCollection")
    private Collection<Permisos> permisosCollection;
    @OneToMany(cascade = CascadeType.ALL, mappedBy = "idRol")
    private Collection<Usuarios> usuariosCollection;

    public Roles() {
    }

    public Roles(Integer idRol) {
        this.idRol = idRol;
    }

    public Integer getIdRol() {
        return idRol;
    }

    public void setIdRol(Integer idRol) {
        this.idRol = idRol;
    }

    public String getNombreRol() {
        return nombreRol;
    }

    public void setNombreRol(String nombreRol) {
        this.nombreRol = nombreRol;
    }

    @XmlTransient
    public Collection<Permisos> getPermisosCollection() {
        return permisosCollection;
    }

    public void setPermisosCollection(Collection<Permisos> permisosCollection) {
        this.permisosCollection = permisosCollection;
    }

    @XmlTransient
    public Collection<Usuarios> getUsuariosCollection() {
        return usuariosCollection;
    }

    public void setUsuariosCollection(Collection<Usuarios> usuariosCollection) {
        this.usuariosCollection = usuariosCollection;
    }

    @Override
    public int hashCode() {
        int hash = 0;
        hash += (idRol != null ? idRol.hashCode() : 0);
        return hash;
    }

    @Override
    public boolean equals(Object object) {
        // TODO: Warning - this method won't work in the case the id fields are not set
        if (!(object instanceof Roles)) {
            return false;
        }
        Roles other = (Roles) object;
        if ((this.idRol == null && other.idRol != null) || (this.idRol != null && !this.idRol.equals(other.idRol))) {
            return false;
        }
        return true;
    }

    @Override
    public String toString() {
        return "entities.Roles[ idRol=" + idRol + " ]";
    }
    
}

src/java/controller/MascotasController.java
package controller;

import controller.login.LoginBean;
import controller.util.SessionUtils;
import entities.Especies;
import entities.Mascotas;
import entities.Veterinarias;
import facade.MascotasFacade;
import facade.VeterinariasFacade;
import java.io.ByteArrayInputStream;
import java.io.Serializable;
import java.util.Calendar;
import java.util.Collection;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.ejb.EJB;
import javax.faces.bean.ManagedBean;
import javax.annotation.PostConstruct;
import javax.enterprise.context.SessionScoped;
import javax.faces.bean.ApplicationScoped;
import javax.faces.event.ActionEvent;
import org.primefaces.event.FileUploadEvent;
import org.primefaces.model.DefaultStreamedContent;
import org.primefaces.model.StreamedContent;
import org.primefaces.model.UploadedFile;

@ManagedBean(name = "mascotasController")
@SessionScoped
@ApplicationScoped
public class MascotasController extends AbstractController<Mascotas> implements Serializable {

    private static final Logger LOGGER = Logger.getLogger(MascotasController.class.getName());

    @EJB
    private MascotasFacade ejbFacade;

    @EJB
    private VeterinariasFacade veterinariasFacade;

    @PostConstruct
    @Override
    public void init() {
        super.setFacade(ejbFacade);
    }

    public MascotasController() {
        super(Mascotas.class);
    }
    private final LoginBean loginBean = new LoginBean();

    @Override
    public void saveNew(ActionEvent event) {
        super.getSelected().setFechaAlta(Calendar.getInstance().getTime());
        super.getSelected().setArchivo(archivo.getContents());
        super.getSelected().setMime(archivo.getContentType());
        if (!loginBean.tieneRol("1")) {
            LoadVeterinaria();
        }
        super.saveNew(event);
        this.archivo = null;
    }

    @Override
    public void save(ActionEvent event) {
        super.getSelected().setArchivo(archivo.getContents());
        super.getSelected().setMime(archivo.getContentType());
        if (!loginBean.tieneRol("1")) {
            LoadVeterinaria();
        }

        super.save(event);
        this.archivo = null;

    }

    private void LoadVeterinaria() {
        javax.servlet.http.HttpSession session = SessionUtils.getSession();
        Integer idVeterinaria = Integer.parseInt(session.getAttribute("veterinaria").toString());
        Veterinarias v = veterinariasFacade.find(idVeterinaria);
        super.getSelected().setIdVeterinaria(v);
    }
    private Especies especie;

    public Especies getEspecie() {
        return especie;
    }

    public void setEspecie(Especies especie) {
        this.especie = especie;
    }

    @Override
    public Collection<Mascotas> getItems() {
        if (loginBean.tieneRol("1")) {
            return super.getItems();
        } else {
            javax.servlet.http.HttpSession session = SessionUtils.getSession();
            Integer idVeterinaria = Integer.parseInt(session.getAttribute("veterinaria").toString());
            return ejbFacade.findAll(idVeterinaria);
        }
    }

    private UploadedFile archivo;

    public UploadedFile getArchivo() {
        return archivo;
    }

    public void setArchivo(UploadedFile archivo) {
        this.archivo = archivo;
    }

    @Override
    public Mascotas prepareCreate(ActionEvent event) {
        this.archivo = null;
        return super.prepareCreate(event); //To change body of generated methods, choose Tools | Templates.
    }

    public void upload(FileUploadEvent event) {
        this.archivo = event.getFile();
        LOGGER.log(Level.INFO, "Uploaded File {0} size: {1}", new Object[]{event.getFile().getFileName(), Long.toString(event.getFile().getSize())});
    }

    private StreamedContent archivoStream;
    public StreamedContent getArchivoStream() {
        Mascotas masc = super.getSelected();
        try {
            ByteArrayInputStream stream = new ByteArrayInputStream(masc.getArchivo());
            archivoStream = new DefaultStreamedContent(stream, masc.getMime());
        } catch (Exception e) {
            LOGGER.log(Level.SEVERE, "ERROR", e);
            archivoStream = new DefaultStreamedContent();
        }
        return archivoStream;
    }
}

src/java/controller/RolesController.java
package controller;

import entities.Roles;
import facade.RolesFacade;
import java.io.Serializable;
import javax.ejb.EJB;
import javax.faces.bean.ManagedBean;
import javax.faces.bean.ViewScoped;
import javax.annotation.PostConstruct;

@ManagedBean(name = "rolesController")
@ViewScoped
public class RolesController extends AbstractController<Roles> implements Serializable {

    @EJB
    private RolesFacade ejbFacade;

    @PostConstruct
    @Override
    public void init() {
        super.setFacade(ejbFacade);
    }

    public RolesController() {
        super(Roles.class);
    }

}

web/secure/roles/Create.xhtml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:ui="http://java.sun.com/jsf/facelets"
      xmlns:h="http://java.sun.com/jsf/html"
      xmlns:f="http://java.sun.com/jsf/core"
      xmlns:p="http://primefaces.org/ui">

    <ui:composition>

        <p:dialog id="RolesCreateDlg" widgetVar="RolesCreateDialog" modal="true" resizable="false" appendTo="@(body)" header="#{myBundle.CreateRolesTitle}" closeOnEscape="true">

            <h:form id="RolesCreateForm">

                <h:panelGroup id="display">
                    <p:panelGrid columns="2" columnClasses="column">
                        <p:outputLabel value="#{myBundle.CreateRolesLabel_descripcionRol}" for="descripcionRol" />
                        <p:inputText id="descripcionRol" value="#{rolesController.selected.nombreRol}" title="#{myBundle.CreateRolesTitle_descripcionRol}"/>
                    </p:panelGrid>
                    <p:commandButton actionListener="#{rolesController.saveNew}" value="#{myBundle.Save}" update="display,:RolesListForm:datalist,:growl" oncomplete="handleSubmit(xhr,status,args,PF('RolesCreateDialog'));">
                        <p:confirm header="#{myBundle.ConfirmationHeader}" message="#{myBundle.ConfirmCreateMessage}" icon="ui-icon-alert"/>
                    </p:commandButton>

                    <p:commandButton value="#{myBundle.Cancel}" onclick="RolesCreateDialog.hide()"/>
                </h:panelGroup>

            </h:form>

        </p:dialog>

    </ui:composition>

</html>

web/secure/roles/Edit.xhtml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:ui="http://java.sun.com/jsf/facelets"
      xmlns:h="http://java.sun.com/jsf/html"
      xmlns:f="http://java.sun.com/jsf/core"
      xmlns:p="http://primefaces.org/ui">

    <ui:composition>
        <p:dialog id="RolesEditDlg" widgetVar="RolesEditDialog" modal="true" resizable="false"  appendTo="@(body)" header="#{myBundle.EditRolesTitle}" closeOnEscape="true">

            <h:form id="RolesEditForm">

                <h:panelGroup id="display">
                    <p:panelGrid  columns="2" columnClasses="column" rendered="#{rolesController.selected != null}">


                        <h:outputLabel value="#{myBundle.EditRolesLabel_idRol}" for="idRol" />
                        <h:outputText id="idRol" value="#{rolesController.selected.idRol}" />

                        <p:outputLabel value="#{myBundle.EditRolesLabel_descripcionRol}" for="descripcionRol" />
                        <p:inputText id="descripcionRol" value="#{rolesController.selected.nombreRol}" title="#{myBundle.EditRolesTitle_descripcionRol}"/>
                    </p:panelGrid>
                    <p:commandButton actionListener="#{rolesController.save}" value="#{myBundle.Save}" update="display,:RolesListForm:datalist,:growl" oncomplete="handleSubmit(xhr,status,args,PF('RolesEditDialog'));">
                        <p:confirm header="#{myBundle.ConfirmationHeader}" message="#{myBundle.ConfirmEditMessage}" icon="ui-icon-alert"/>
                    </p:commandButton>
                    <p:commandButton value="#{myBundle.Cancel}" onclick="RolesEditDialog.hide()"/>
                </h:panelGroup>

            </h:form>

        </p:dialog>

    </ui:composition>

</html>

web/secure/roles/List.xhtml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<ui:composition xmlns="http://www.w3.org/1999/xhtml"
                xmlns:ui="http://java.sun.com/jsf/facelets"
                xmlns:h="http://java.sun.com/jsf/html"
                xmlns:f="http://java.sun.com/jsf/core"
                xmlns:p="http://primefaces.org/ui">

    <h:form id="RolesListForm">

        <p:panel header="#{myBundle.ListRolesTitle}">
            <p:contextMenu for="datalist">  
                <p:menuitem id="createMenuItem" icon="ui-icon-plus" value="#{myBundle.Create}" onclick="document.getElementById('RolesListForm:createButton').click();"/>
                <p:menuitem id="readMenuItem" icon="ui-icon-search" value="#{myBundle.View}" onclick="document.getElementById('RolesListForm:viewButton').click();"/>
                <p:menuitem id="updateMenuItem" icon="ui-icon-pencil" value="#{myBundle.Edit}" onclick="document.getElementById('RolesListForm:editButton').click();"/>
                <p:menuitem id="deleteMenuItem" icon="ui-icon-trash" value="#{myBundle.Delete}" onclick="document.getElementById('RolesListForm:deleteButton').click();"/>
            </p:contextMenu>
            <p:dataTable id="datalist"
                         value="#{rolesController.items}"
                         var="item"
                         rowKey="#{item.idRol}"
                         paginator="true"
                         rows="10"
                         rowsPerPageTemplate="10,20,30,40,50"
                         selectionMode="single"
                         selection="#{rolesController.selected}">

                <p:ajax event="rowSelect"   update=":RolesListForm:createButton :RolesListForm:viewButton :RolesListForm:editButton :RolesListForm:deleteButton"/>
                <p:ajax event="rowUnselect" update=":RolesListForm:createButton :RolesListForm:viewButton :RolesListForm:editButton :RolesListForm:deleteButton"/>
                <p:ajax event="rowDblselect" onsuccess="document.getElementById('RolesListForm:viewButton').click();"/>

                <p:column sortBy="#{item.idRol}" filterBy="#{item.idRol}">
                    <f:facet name="header">
                        <h:outputText value="#{myBundle.ListRolesTitle_idRol}"/>
                    </f:facet>
                    <h:outputText value="#{item.idRol}"/>
                </p:column>


                <p:column sortBy="#{item.nombreRol}" filterBy="#{item.nombreRol}">
                    <f:facet name="header">
                        <h:outputText value="#{myBundle.ListRolesTitle_descripcionRol}"/>
                    </f:facet>
                    <h:outputText value="#{item.nombreRol}"/>
                </p:column>


            </p:dataTable>

            <p:commandButton id="createButton"                             icon="ui-icon-plus"   value="#{myBundle.Create}" actionListener="#{rolesController.prepareCreate}" update=":RolesCreateForm" oncomplete="PF('RolesCreateDialog').show()"/>
            <p:commandButton id="viewButton"   style="visibility: hidden;" icon="ui-icon-search" value="#{myBundle.View}" update=":RolesViewForm" oncomplete="PF('RolesViewDialog').show()" disabled="#{empty rolesController.selected}"/>
            <p:commandButton id="editButton"   style="visibility: hidden;" icon="ui-icon-pencil" value="#{myBundle.Edit}" update=":RolesEditForm" oncomplete="PF('RolesEditDialog').show()" disabled="#{empty rolesController.selected}"/>
            <p:commandButton id="deleteButton" style="visibility: hidden;" icon="ui-icon-trash"  value="#{myBundle.Delete}" actionListener="#{rolesController.delete}" update=":growl,datalist" disabled="#{empty rolesController.selected}">
                <p:confirm header="#{myBundle.ConfirmationHeader}" message="#{myBundle.ConfirmDeleteMessage}" icon="ui-icon-alert"/>
            </p:commandButton>

        </p:panel>
        <ui:include src="/secure/confirmation.xhtml"/>
    </h:form>

</ui:composition>

web/secure/roles/View.xhtml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:ui="http://java.sun.com/jsf/facelets"
      xmlns:h="http://java.sun.com/jsf/html"
      xmlns:f="http://java.sun.com/jsf/core"
      xmlns:p="http://primefaces.org/ui">

    <ui:composition>

        <p:dialog id="RolesViewDlg" widgetVar="RolesViewDialog" modal="true" resizable="false"  appendTo="@(body)" header="#{myBundle.ViewRolesTitle}" closeOnEscape="true">

            <h:form id="RolesViewForm">

                <h:panelGroup id="display">
                    <p:panelGrid columns="2" columnClasses="column" rendered="#{rolesController.selected != null}">

                        <h:outputText value="#{myBundle.ViewRolesLabel_idRol}"/>
                        <h:outputText value="#{rolesController.selected.idRol}" title="#{myBundle.ViewRolesTitle_idRol}"/>

                        <h:outputText value="#{myBundle.ViewRolesLabel_descripcionRol}"/>
                        <h:outputText value="#{rolesController.selected.nombreRol}" title="#{myBundle.ViewRolesTitle_descripcionRol}"/>
                    </p:panelGrid>
                    <p:commandButton value="#{myBundle.Close}" onclick="RolesViewDialog.hide()"/>
                </h:panelGroup>

            </h:form>

        </p:dialog>

    </ui:composition>

</html>

web/secure/roles/index.xhtml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<ui:composition xmlns:ui="http://java.sun.com/jsf/facelets"
                xmlns:h="http://java.sun.com/jsf/html"
                xmlns:f="http://java.sun.com/jsf/core"
                xmlns:p="http://primefaces.org/ui"
                template="/secure/template.xhtml">

    <ui:define name="title">
        <h:outputText value="#{myBundle.RolesTitle}"/>
    </ui:define>

    <ui:define name="body">

        <ui:include src="/secure/roles/List.xhtml"/>
        <ui:include src="/secure/roles/View.xhtml"/>
        <ui:include src="/secure/roles/Edit.xhtml"/>
        <ui:include src="/secure/roles/Create.xhtml"/>

    </ui:define>

</ui:composition>